import { PrismaService } from '../prisma/prisma.service';
import { Role } from '@prisma/client';
export declare class UsersService {
    private prisma;
    constructor(prisma: PrismaService);
    findById(id: string): Promise<{
        id: string;
        email: string;
        googleId: string | null;
        name: string;
        passwordHash: string | null;
        phone: string | null;
        role: import("@prisma/client").$Enums.Role;
        companyName: string | null;
        gstin: string | null;
        billingAddress: string | null;
        shippingAddress: string | null;
        profilePhoto: string | null;
        isEmailVerified: boolean;
        isDisabled: boolean;
        createdAt: Date;
        updatedAt: Date;
    } | null>;
    findByEmail(email: string): Promise<{
        id: string;
        email: string;
        googleId: string | null;
        name: string;
        passwordHash: string | null;
        phone: string | null;
        role: import("@prisma/client").$Enums.Role;
        companyName: string | null;
        gstin: string | null;
        billingAddress: string | null;
        shippingAddress: string | null;
        profilePhoto: string | null;
        isEmailVerified: boolean;
        isDisabled: boolean;
        createdAt: Date;
        updatedAt: Date;
    } | null>;
    findByGoogleId(googleId: string): Promise<{
        id: string;
        email: string;
        googleId: string | null;
        name: string;
        passwordHash: string | null;
        phone: string | null;
        role: import("@prisma/client").$Enums.Role;
        companyName: string | null;
        gstin: string | null;
        billingAddress: string | null;
        shippingAddress: string | null;
        profilePhoto: string | null;
        isEmailVerified: boolean;
        isDisabled: boolean;
        createdAt: Date;
        updatedAt: Date;
    } | null>;
    create(data: {
        name: string;
        email: string;
        passwordHash?: string;
        googleId?: string;
        role?: Role;
        isEmailVerified?: boolean;
    }): Promise<{
        id: string;
        email: string;
        googleId: string | null;
        name: string;
        passwordHash: string | null;
        phone: string | null;
        role: import("@prisma/client").$Enums.Role;
        companyName: string | null;
        gstin: string | null;
        billingAddress: string | null;
        shippingAddress: string | null;
        profilePhoto: string | null;
        isEmailVerified: boolean;
        isDisabled: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateProfile(id: string, data: {
        name?: string;
        phone?: string;
        companyName?: string;
        gstin?: string;
        billingAddress?: string;
        shippingAddress?: string;
        profilePhoto?: string;
    }): Promise<{
        id: string;
        email: string;
        googleId: string | null;
        name: string;
        passwordHash: string | null;
        phone: string | null;
        role: import("@prisma/client").$Enums.Role;
        companyName: string | null;
        gstin: string | null;
        billingAddress: string | null;
        shippingAddress: string | null;
        profilePhoto: string | null;
        isEmailVerified: boolean;
        isDisabled: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateRole(id: string, role: Role): Promise<{
        id: string;
        email: string;
        googleId: string | null;
        name: string;
        passwordHash: string | null;
        phone: string | null;
        role: import("@prisma/client").$Enums.Role;
        companyName: string | null;
        gstin: string | null;
        billingAddress: string | null;
        shippingAddress: string | null;
        profilePhoto: string | null;
        isEmailVerified: boolean;
        isDisabled: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateDisabledStatus(id: string, isDisabled: boolean): Promise<{
        id: string;
        email: string;
        googleId: string | null;
        name: string;
        passwordHash: string | null;
        phone: string | null;
        role: import("@prisma/client").$Enums.Role;
        companyName: string | null;
        gstin: string | null;
        billingAddress: string | null;
        shippingAddress: string | null;
        profilePhoto: string | null;
        isEmailVerified: boolean;
        isDisabled: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findAll(): Promise<{
        id: string;
        email: string;
        googleId: string | null;
        name: string;
        passwordHash: string | null;
        phone: string | null;
        role: import("@prisma/client").$Enums.Role;
        companyName: string | null;
        gstin: string | null;
        billingAddress: string | null;
        shippingAddress: string | null;
        profilePhoto: string | null;
        isEmailVerified: boolean;
        isDisabled: boolean;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
}
